export enum Icon {
  NONE = "",
  RAISE = "raise",
  CHEVRON_DOWN = "chevron-down",
  CHEVRON_RIGHT = "chevron-right",
  EDIT = "edit",
  COPY = "copy",
  PREVIEW = "preview",
  SEARCH = "search",
  TERMINATE = "terminate",
  PLUS_IN_CIRCLE = "plus-in-circle",
  DELETE = "delete",
  QUESTION = "question",
  DOWNLOAD = "download",
  EXPAND = "expand",
  COLLAPSE = "collapse",
  PRINT = "print",
  SHARE = "share",
  STATUS_CONSIDERED = "status-considered",
  STATUS_DECLINED = "status-declined",
  STATUS_ACCEPTED = "status-accepted",
  CLOSE = "close",
  PROFILE = "profile",
  RECOMMENDED_STAR = "recommended-star",
  APPLICATION_CV = "application-cv",
  TRASH_BIN = "trash-bin",
}

export enum IconColor {
  WHITE = "white",
  LIGHT_GRAY = "light-gray",
  DARK_GRAY = "dark-gray",
  SUCCESS_GREEN = "success-green",
  LINK_BLUE = "link-blue",
}
